[default]
exten => s,1,NoOp(Default context)
 same => n,Hangup()

[from-internal]
exten => _X.,1,NoOp(Internal call from agent)
 same => n,Answer()
 same => n,Stasis(dialer-app)
 same => n,Hangup()

[from-external]
exten => _X.,1,NoOp(External trunk path)
 same => n,Stasis(dialer-app)
 same => n,Hangup()

[from-web]
exten => _X.,1,NoOp(Browser SIP/WebRTC call to ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN}@mytrunk-endpoint,30)
 same => n,Hangup()
