[global]
type=global
user_agent=DialerStarter

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0


; ---------- Example SIP trunk ----------
[mytrunk-auth]
type=auth
auth_type=userpass
username=1001
password=ecp!gen@20129

[mytrunk-aor]
type=aor
contact=sip:1001@172.16.50.45

[mytrunk-endpoint]
type=endpoint
transport=transport-udp
context=from-external
disallow=all
allow=ulaw,alaw
outbound_auth=mytrunk-auth
aors=mytrunk-aor
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[mytrunk-identify]
type=identify
endpoint=mytrunk-endpoint
match=172.16.50.45

; ---------- Browser SIP.js endpoint ----------
; Loaded from the generated pjsip.browser.conf file at container start.
#include pjsip.browser.conf

; ---------- Example agent endpoint 1001 ----------
[1001-auth]
type=auth
auth_type=userpass
username=1001
password=ecp!gen@20129

[1001-aor]
type=aor
max_contacts=1

[1001]
type=endpoint
transport=transport-udp
context=from-internal
disallow=all
allow=ulaw,alaw
auth=1001-auth
aors=1001-aor
direct_media=no
rewrite_contact=yes
rtp_symmetric=yes
force_rport=yes
